import type { Metadata } from "next";
import { Montserrat as FontSans } from "next/font/google";

import "./globals.css";

import { notFound } from "next/navigation";
import { ReactNode } from "react";

import { Footer } from "@/components/footer/footer-site";
import { Header } from "@/components/header/header-site";
import { TolgeeNextProvider } from "@/lib/tolgee/client";
import { ALL_LOCALES, getStaticData } from "@/lib/tolgee/shared";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: ReactNode;
  params: { locale: string };
};
export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<Props>) {
  if (!ALL_LOCALES.includes(locale)) {
    notFound();
  }

  const locales = await getStaticData([locale]);
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "flex min-h-screen flex-col bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <TolgeeNextProvider locale={locale} locales={locales}>
          <Header />
          <main className="flex-[1_0_auto]">{children}</main>
          <Footer />
        </TolgeeNextProvider>
      </body>
    </html>
  );
}
