import type { Metadata } from "next";
import { Montserrat as FontSans } from "next/font/google";

import "./globals.css";

import { notFound } from "next/navigation";
import { ReactNode, Suspense } from "react";

import Providers from "./providers";

import { Icons } from "@/components/ui/icons";
import { TolgeeNextProvider } from "@/lib/tolgee/client";
import { ALL_LOCALES, getStaticData } from "@/lib/tolgee/shared";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: ReactNode;
  params: { locale: string };
};
export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<Props>) {
  if (!ALL_LOCALES.includes(locale)) {
    notFound();
  }

  const locales = await getStaticData([locale]);
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body
        className={cn(
          "flex min-h-screen flex-col bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Suspense
          fallback={
            <div className="flex h-screen items-start justify-center bg-black">
              <Icons.spinner className="size-8 animate-spin" />
            </div>
          }
        >
          <TolgeeNextProvider locale={locale} locales={locales}>
            <Providers>{children}</Providers>
          </TolgeeNextProvider>
        </Suspense>
      </body>
    </html>
  );
}
